[package]
name = "redis_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
atoi = "2.0.0"
bytes = "1.4.0"
structopt = "0.3.26"
tokio = "1.29.1"
